version: '3.8'  

services:

  mysql:
    container_name: bd_medtech
    image: davifeitosa0/bd_medtech
    ports:
      - "3306:3306"

  appcliente:  
    container_name: jar_davi
    image: davifeitosa0/jar_davi
    environment:
      -  CODIGO_PATRIMONIO=C056694
      -  SENHA_PC=medtech88 
    depends_on:
      - mysql

  
    
